### ISSUE TITLE
Is it supported to specify custom start and end date to download flex query reports?

### ISSUE THREAD

**Issue by WalkerWalker** [csingley/ibflex#46]
Wow.  It's great to find this repo.  Exactly what I need.   Thank you so much. 

Sorry if this issue doesn't belong here. Maybe it should be a question for the IBKR platform. As indicated in the title, is it supported to specify custom start and end date to download flex query reports? I want to download three years of trading confirmation and I am not sure if it's possible with the flex query api.  If I can specify the date, then I can first download the report for year 2019, then for year 2020 and then year to date in 2021. 

Thanks!

**Comment by csingley** [comment]
This is not something that `ibflex` can handle for you, but yes, you can do this on IBKR's website.  Go poke around in your account and I'm you'll figure it out.

Then once you've got your trade confirmations, you can use this library to import them into Python and play with them.  That's what it's for.

Good luck!
