### ISSUE TITLE
CFD in AssetClass

### ISSUE THREAD

**Issue by kharteveld** [csingley/ibflex#6]
Hi, Could you please add CFD to the AssetClass Enum? Thanks.

**Comment by csingley** [comment]
[Your wish is my command](https://github.com/csingley/ibflex/commit/cb0f007c706f47631b6d7194abe72790c6a74b09), oh exalted arbitrageur.

**Comment by kharteveld** [comment]
Wow, that’s fast! Thanks a lot!
