### ISSUE TITLE
AttributeError: module 'ibflex.Types' has no attribute 'AssetSummary'

### ISSUE THREAD

**Issue by zdomokos** [csingley/ibflex#7]
Trying to parse my report, and always get this error.

**Comment by csingley** [comment]
We don't have <AssetSummary> yet, it must be new.

If you send me one, I'll add it to ibflex.Types.  I doubt there's any sensitive information in such an element, but if there is, just redact it.

**Comment by csingley** [comment]
You could also just uncheck that box in the Flex report until I get a chance to update the types.

**Comment by csingley** [comment]
OK I figured this out.  `<AssetSummary>` isn't a new type.  You simply missed [this section](https://github.com/csingley/ibflex#flex-query-report-configuration) of the extremely high-quality documentation:

> For the Trades section of the statement, you can't select the options at the top for "Symbol Summary", "Asset Class", or "Orders". These will blow up the parser.

That will fix your problem.
