### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'FlexStatements'

### ISSUE THREAD

**Issue by MarioColombo** [csingley/ibflex#72]
Hi,
I'm trying to use it.
I got the response well with
response = client.download(token, query_id)
But trying to ge the statement gives me an error:
stmt = response.FlexStatements[0]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[57], line 1
----> 1 stmt = response.FlexStatements[0]

AttributeError: 'bytes' object has no attribute 'FlexStatements'

**Comment by csingley** [comment]
If you’re not a programmer, you’re going to have a bad time using this library.

**Comment by eyalk11** [comment]
See this example 

```
    def doquery(self):
        logging.info(("running query in IB  for transaction"))
        if not self.DoQuery or not (self.query_id) or not self.token_id:
            return
        try:
            response = client.download(self.token_id, self.query_id)
        except:
            logging.debug(('err in querying flex'))
            import traceback;traceback.print_exc()
            return

        p = parser.parse(response)
        return  p.FlexStatements[0].Trades
```
